Keystatic docs site
Thinkmill/keystatic pull request #271
Opened 2023-05-15 07:13 UTC by BarnabyBishop

Still a bit of a WIP, but this PR contains the new Keystatic website, with docs which are managed in its own keystatic setup.

- Copied keystatic-site into the docs folder
- Added `/docs` section to the docs site with content editable in keystatic
- Added a bunch of content
- Changed voussoir npm scripts from `docs` to `designsystem`, e.g. `npm run build:docs` -> `npm run build:designsystem` so we could steal the docs commands (sorry Joss). I'll update the voussior vercel app with this change before merging.

2023-05-15 07:34 UTC, jtbrolin commented on docs/public/images/templates/blog@2x.png
Just noticed that the @1x and @2x versions are different from the @3x version, and looks like @3x is the only one being used

2023-05-15 23:03 UTC, ChrisLaneAU commented on docs/README.md
> +To submit forms to airtable, you need to add a `.env` file in the project root with the following environment variables:
Should we have a `.env.example`?

2023-05-15 23:12 UTC, ChrisLaneAU commented on docs/next.config.js
> +    appDir: true,
Do we still need this now that the app router is stable? I don't actually know 🤷

2023-05-15 23:18 UTC, ChrisLaneAU commented on docs/public/images/templates/blog@2x.png
I can fix this in my images PR + ancillary tasks

2023-05-15 23:19 UTC, ChrisLaneAU commented on docs/public/safari-pinned-tab.svg
Is this image correct?

2023-05-15 23:26 UTC, emmatown requested changes
I'll probably have thoughts on a bunch of this but I can review it async. I just have one blocking concern: the fonts and images bloating this repo. For the site icons, just have a single `icon.svg` in the `app` directory. For the other images, could you put them in an R2 bucket or something? For the font, use `next/font`.

2023-05-15 23:35 UTC, ChrisLaneAU commented on docs/src/app/docs/page.tsx
> +      <h2 className="text-3xl font-bold sm:text-4xl">
Should this be `h1`?

2023-05-16 00:02 UTC, emmatown commented
For now, have a custom block with a text field for the image url

2023-05-16 04:15 UTC, BarnabyBishop commented
Closing the PR as we no-longer need it right now. 

All PR feedback has been put in Linear.

2023-05-16 04:15 UTC, closed without merging