Dynamic og images
Thinkmill/keystatic pull request #451
Opened 2023-07-14 04:06 UTC by simonswiss

Adds an `/og` API route that generates an OG image based on the `title` query parameter passed to it.

Uses a PNG background image as the base (hosted on Keystatic Cloud):

<img width="675" alt="CleanShot 2023-07-14 at 14 02 29@2x" src="https://github.com/Thinkmill/keystatic/assets/485747/47730d1f-7023-4a70-abb6-3fc7e24165cc">

It then plops in the title onto it to generate the final image.

For example: `/og?title=Hello+world`.

<img width="376" alt="CleanShot 2023-07-14 at 14 01 00@2x" src="https://github.com/Thinkmill/keystatic/assets/485747/9fc08f91-9fb7-44dc-b65f-dec4a275fd1b">

2023-07-14 04:28 UTC, emmatown requested changes
🙅‍♀️ to committing a font file to the repo

2023-07-14 09:20 UTC, JedWatson approved these changes

2023-07-14 09:21 UTC, JedWatson commented
@emmatown are you going to approve now you've updated it to include the font as a dependency?

2023-07-17 00:04 UTC, emmatown approved these changes

2023-07-17 10:31 UTC, merged