Filter out DOM props TableVirtualizer
Thinkmill/keystatic pull request #815
Opened 2023-12-10 21:42 UTC by stephan281094

Hi there! First of all, thank you so much for the amazing work you've been doing with Keystatic!

Recently I've noticed some browser console errors whenever landing on a collection page inside of Keystatic's Admin UI:

![Screenshot 2023-12-10 at 13 23 08](https://github.com/Thinkmill/keystatic/assets/4006802/7c2e593b-1633-4b90-8452-50ec2a791445)

Turns out, DOM props were being passed to an element inside of the `TableVirtualizer` component, when they should've been filtered out. This pull request fixes that.

2023-12-10 22:19 UTC, jossmac approved these changes

2023-12-10 22:21 UTC, jossmac requested changes
Looks good, thanks for this. Just needs a changeset: run `pnpm changeset`.

2023-12-10 22:25 UTC, stephan281094 commented
Thanks for the review @jossmac. Changeset added!

2023-12-11 00:44 UTC, emmatown approved these changes

2023-12-11 00:50 UTC, merged